- hosts: win
  vars:
    # 应用服务器发版的主机,等待传参
    dsthosts: 192.168.156.71
    # 执行的命令等待传参
    cmds: "dir"
  tasks:
  - name: execcmds        | 执行命令
    shell: "{{ cmds }}"
    register: cmd_out
    
  - name: echo cmd_out    | 打印命令执行结果
    debug: var=cmd_out